### ISSUE TITLE
log_discord.py doesn't work

### ISSUE THREAD

**Issue by tomillo** [haccer/discord-scripts#1]
Hi! I'm trying to relay and log to a file, but it doesn't work. It's frozen in "Logged in as blabla - 564451545455"

**Comment by haccer** [comment]
Hi @tomillo, 

I've recently just tested log_discord.py to confirm it does work.

>  It's frozen in "Logged in as blabla - 564451545455"

There's not supposed to be any output to the terminal. Have you configured the channel id's correctly?

**Comment by tomillo** [comment]
Yes. I’m sorry for that. Now it works!
I have another question. There’s a way to send to channel with bot and not with my user?
Also, can I configure more than one channel to log and relay messages?

**Comment by haccer** [comment]
>I have another question. There’s a way to send to channel with bot and not with my user?

Yeah, probably if you used your bots token. 

> Also, can I configure more than one channel to log and relay messages?

Yes, that'd require extra coding. Just create more `if` statements in the script similar to the one that's there. I'll edit the script a bit right now to make it easier.

The [discord.py](https://github.com/Rapptz/discord.py) api docs are [here](http://discordpy.readthedocs.io/en/latest/), in case you need help.

**Comment by tomillo** [comment]
Thank you very much for helping me!
