### ISSUE TITLE
Doesn't work. 

### ISSUE THREAD

**Issue by Cutebutt** [haccer/discord-scripts#3]
Should this be working with BetterDiscord? I have made it log text into .txt in the same folder and it's correctly pathed. All the .py says when open is "Logged in as *****" and my name. But if anyone writes, it doesn't log anything.

It's compatible with BD right? Do I need to know more about coding. I replaced id's what I needed to replace with and token also. But I have changed nothing else.

**Comment by Cutebutt** [comment]
Do I have to change something in the log_discord\log_discord.py ?

**Comment by Cutebutt** [comment]
Like I'm not selfbot right at this moment

**Comment by Cutebutt** [comment]
Aaalso. What to do with the .service file? Since I'm using the .txt file myself.

**Comment by haccer** [comment]
I've never used BetterDiscord before, but everything in this repository I use daily and share w/ people who've asked lol.

The .service is for systemd and not neccessary to use log_discord.py.

In log_discord.py, you'll have to change the IDs and configured it to log the channels you wish. See README.md for configuration instructions.
